Práctica 2 Métodos de Validación
I. Utilizando el dataset metodosDeValidacion.csv elabore un programa en python que realice lo siguiente:
    • Sin mezclar los datos genere un conjunto de entrenamiento (60%) y uno de prueba (40%).
    • Con validación cruzada genere conjuntos de validación para k=3.
    • Genere conjuntos de validación con Leave One Out
    • Utilizando Bootstrap genere 2 conjuntos de validación con conjuntos de entrenamiento de tamaño=5

II.El programa deberá imprimir en pantalla los conjuntos de validación
generados por cada método de validación

In [1]:
#Importar liberias
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold
from sklearn.utils import resample

C:\Users\acer\AppData\Local\Temp\ipykernel_9312\2538196825.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
# Funcion para la validación cruzada
def validacionCruzada(X_train,y_train,k):
	print ('\n ----------------------\n')
	print ('\n Validación cruzada \n')
	kf = KFold(n_splits=k)
	print ('\n X \n')
	for train, test in kf.split(X_train):
		print(X_train[train], X_train[test])
	print ('\n y \n')
	for train, test in kf.split(X_train):
		print('train',y_train[train], 'test' ,y_train[test])

# Funcion LeaveOneOut
def dejaUnoFuera(X_train,y_train):
	print ('\n ----------------------\n')
	print ('\n LeaveOneOut')
	loo = LeaveOneOut()
	print (loo.get_n_splits(X_train))
	print ('\n X \n')
	for i, (train_index, test_index) in enumerate(loo.split(X_train)):
		print('\n',i,X_train[train_index], X_train[test_index])
	print ('\n y \n')
	for i, (train_index, test_index) in enumerate(loo.split(X_train)):
		print('\n',i,'train',y_train[train_index], 'test' ,y_train[test_index])

#Funcion para el bootstrap
def bootstrap(X_train,y_train,nc,m):
	print ('\n ----------------------\n')
	print ('\n Bootstrap')
	print ('\n X \n')
	for i in range(nc):
		train = resample(X_train, n_samples = m)
		test = np.array([x for x in X_train if x not in train])
		print ('train',train,'test',test)
	print ('\n y')
	for i in range(nc):
		train = resample(y_train, n_samples = m)
		test = np.array([x for x in y_train if x not in train])
		print ('train',train,'test',test)
	print ('\n')

In [3]:
df = pd.read_csv('metodosDeValidacion.csv',sep=',')
print(df)

     x   y
0    1   2
1    2   4
2    3   6
3    4   8
4    5  10
5    6  12
6    7  14
7    8  16
8    9  18
9   10  20
10  11  22
11  12  24
12  13  26
13  14  28
14  15  30
15  16  32
16  17  34
17  18  36
18  19  38
19  20  40


In [4]:
X = df[['x']].values
y = df['y'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, shuffle=False)
print ('\n X_train \n',X_train)
print ('\n X_test \n',X_test)
print ('\n y_train \n',y_train)
print ('\n y_test \n',y_test)


 X_train 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

 X_test 
 [[13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]

 y_train 
 [ 2  4  6  8 10 12 14 16 18 20 22 24]

 y_test 
 [26 28 30 32 34 36 38 40]


In [8]:
validacionCruzada(X_train,y_train,3)


 ----------------------


 Validación cruzada 


 X 

[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[1]
 [2]
 [3]
 [4]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 9]
 [10]
 [11]
 [12]] [[5]
 [6]
 [7]
 [8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] [[ 9]
 [10]
 [11]
 [12]]

 y 

train [10 12 14 16 18 20 22 24] test [2 4 6 8]
train [ 2  4  6  8 18 20 22 24] test [10 12 14 16]
train [ 2  4  6  8 10 12 14 16] test [18 20 22 24]


In [6]:
dejaUnoFuera(X_train,y_train)


 ----------------------


 LeaveOneOut
12

 X 


 0 [[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[1]]

 1 [[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[2]]

 2 [[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[3]]

 3 [[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[4]]

 4 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[5]]

 5 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[6]]

 6 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] [[7]]

 7 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]
 [11]
 [12]] [[8]]

 8 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]] [[9]]

 9 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [11]
 [12]] [[10]]

 10 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [12]] [[11]]

 11 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] [[12]]

 y 


 0 train [ 4  6

In [7]:
bootstrap(X_train,y_train,2,5)


 ----------------------


 Bootstrap

 X 

train [[7]
 [7]
 [4]
 [7]
 [7]] test [[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
train [[3]
 [8]
 [1]
 [8]
 [5]] test [[ 2]
 [ 4]
 [ 6]
 [ 7]
 [ 9]
 [10]
 [11]
 [12]]

 y
train [ 2 24 14 22 10] test [ 4  6  8 12 16 18 20]
train [ 6 14  2 18  2] test [ 4  8 10 12 16 20 22 24]


